description: catdog_single_train
data:
  pachyderm:
    host: localhost
    port: 80
    project: catdog
    repo: compress
    commit: fbc3668bd5434ba6b918b07290371207
hyperparameters:
  learning_rate: 0.005
  global_batch_size: 16
  weight_decay: 1.0e-4
  nesterov: true
searcher:
  name: single
  metric: accuracy
  max_length:
    batches: 200
  smaller_is_better: false
entrypoint: model_def:CatDogModel
scheduling_unit: 10
min_validation_period:
  batches: 100
